name: Publish to Docker Hub
env:
  DOCKER_IMAGE: ghcr.io/elseu/sdu-oidc-jwt-provider
on:
  push:
    tags:
      - "v*"
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Log in with Docker Hub
      #   run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      # - name: Build docker image
      #   run: docker build -t $DOCKER_IMAGE .

      # - name: Push to latest
      #   if: github.ref == 'refs/heads/master'
      #   run: docker tag $DOCKER_IMAGE $DOCKER_IMAGE:latest && docker push $DOCKER_IMAGE:latest
      - name: Push to versions
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION_SUFFIX=$(echo ${GITHUB_REF/refs\/tags\//} | sed -E s/[^-]+//)
          MAJOR_VERSION=${GITHUB_REF/refs\/tags\//} | sed -E s/^([0-9]+).*$/\\1/
          MINOR_VERSION=${GITHUB_REF/refs\/tags\//} | sed -E s/^([0-9]+\.[0-9]+).*$/\\1/
          FULL_VERSION=${GITHUB_REF/refs\/tags\//} | sed -E s/^([0-9]+\.[0-9]+\.[0-9]+).*$/\\1/
          echo "Major: $MAJOR_VERSION$VERSION_SUFFIX"
          echo "Minor: $MINOR_VERSION$VERSION_SUFFIX"
          echo "Full:  $FULL_VERSION$VERSION_SUFFIX"
